### ISSUE TITLE
As a bdp-maintainer I have to update our CI so to successfully run in the testing environment the new Parking DC by edp

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/bdp-commons#30]
- [x] edpprogetti creates a new commit for stationcode names concatenating a municipality prefix and a cleaned station name
- [x] Import parking-tn from edpprogetti
- [x] Update Jenkinsfile CI to test parking-tn
- [x] Fix surefire plugin issues with new Java versions on Debian
- [x] Create a Jenkins pipeline to run parking-tn DC on our test environment

**Comment by bertolla** [comment]
@rcavaliere You can check the testing db if data is correctly inserted

**Comment by bertolla** [comment]
@rcavaliere  you can also check here http://tomcat.testingmachine.eu/parking-ws

**Comment by Piiit** [comment]
@rcavaliere It is on production now, please test on Postgres if you can see the correct stations and measurements after 1pm...

**Comment by bertolla** [comment]
Hi guys,
@rcavaliere @Piiit 
It is now in production but data is missing. Trento is working well but Roveretos live data is missing completely. I checked on the test-environment and there it's the same situation. Is this done on purpose to show that data is missing or is our implementation not working correctly?

Furthermore there is one station in Rovereto where it's coordinates are in Campolongo. Who should fix this?

**Comment by rcavaliere** [comment]
DC seems to work fine. Current issues are related to data provider. Let's check the data flow and I will eventually contact the data provider to improve the LoS.
