### ISSUE TITLE
As a company developing Bluetooth boxes, I would like to have an alternative system to the current VPN for connecting the boxes to the ODH

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/bdp-commons#37]
- [ ] install OpenVPN server on AWS (use configuration in annex) [see attached file]
- [ ] provide connection details for CISMA (for the configuration of the firmware in the box)
[181130_openvpn-config.tar.gz](https://github.com/idm-suedtirol/bdp-commons/files/2638178/181130_openvpn-config.tar.gz)

**Comment by ohnewein** [comment]
@rcavaliere can you please organize a meeting with Endian to see, if they have a solution which would work out of the box?

**Comment by ohnewein** [comment]
I thought the vpn was also used to be able to connect to a box from remote.

Would this be still possible without vpn?

**Comment by rcavaliere** [comment]
I think so, therefore I have asked CISMA to check. I would rather to simplify than make things more complex :-)

**Comment by bertolla** [comment]
Hi guys,
The sending of the data was never meant through VPN. Just the connection to the single boxes and the remote mantainance was done through a VPN. Since we do not have a lot of experience with VPN's and Endian is kind of the expert with it, why not involve them. Furthermore we will have way more Boxes and therefore we need a reliable system of accessing these Boxes, not as we had before.
Patrick

**Comment by rcavaliere** [comment]
@bertolla  @ohnewein Some news here. Stefano G. can provide us the export of the OpenVPN server which actually is installed on traffic.integreen-life.bz.it (62.146.6.205) - German Data Center. CISMA will manage the box, therefore I have agreed with them that they will host this server in the future. The only problem is the timing: CISMA is in the progress to enter in the new NOI building and has some issues with their network (until February and March). Therefore we need a temporary solution to not stop all activities related to the Bluetooth boxes: my proposal is to make a clone of the current OpenVPN server on AWS. Stefano G. will provide us the export of the current configuration. What do you think?

**Comment by ohnewein** [comment]
The VPN and monitoring will be done by the hardware provider
