### ISSUE TITLE
As a traffic engineer, I want to see the new AQ Data Collector developed by Datatellers (APPABZ open data) integrated in the ODH infrastructure

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/bdp-commons#49]

**Comment by rcavaliere** [comment]
Didn't they provide it already? Can you please ping them (Francesco Vettoretti)?

**Comment by bertolla** [comment]
Application is now running under testing.
@rcavaliere 
There is a lot of overlap with the things Peter did. And right now we have double content with same stations and same types. Can you check what informations we already get from the dc-airquality datacollector to avoid to have duplicates and also to not loose data.
First thing I would do is to name same types and same stations to the same identifier, so no duplicates should theoretically be created. For this to work we need to do a good comparison.

**Comment by rcavaliere** [comment]
@bertolla I know this, I will check it carefully. Thanks for the work so far

**Comment by rcavaliere** [comment]
@bertolla definitely we have a duplication problem here and we have to fix this otherwise we have trobules in using / visualizing these stations. You can easily check this by looking at the stationcode attribute, e.g. station BZ4 is the same station with code APPABZ_BZ4. What would happen if we try to save to in the table two records with the same station code?
Can't we have a logic in the core that works like that?
- if stationcode is already present in table station -> don't create a new station, let's create an association with the already existing station
- if stationcode is not present -> create a new station
We could have the same logic with the types but in my view this is not strictly necessary (we should implement this in a new version of the core, as we already discussed...).
@Piiit what do you think about this?

**Comment by Piiit** [comment]
@rcavaliere 
The data collector creates the mapping. That is, if the DC creates a new station, that is already present, it will not overwrite the existing one. However, this must be done already on the DC side. The developer of the DC should have a list of stations, that are already assigned and use the same names. The writer also provides a list of stations with `/stations/{stationType}` and eventually also the origin as parameter....

Succo :-)
If DC developers do not take care about the same stationID, then the writer does not know that is the same...

**Comment by rcavaliere** [comment]
@Piiit thanks for the explanation
@bertolla shall we give these instructions to Datatellers?

**Comment by rcavaliere** [comment]
Sent mail to datatellers with the request to fix the DC (save the stationcode as it is, this will create automatically the mapping with the stations we have in the system)

**Comment by bertolla** [comment]
@Piiit Maybe you could check if it works correctly since you wrote the collector with which it might conflict.

**Comment by rcavaliere** [comment]
Has the new pull request by Datatellers integrated in the CI and deployed on the testing environment? I still see the old station codes in the table station...

**Comment by Piiit** [comment]
@rcavaliere @bertolla FYI
It is on testing now, although I had to fix 3 things:
- Tests failed, becaused they checked for the station prefix, that has been removed
- Station codes were not splitted correctly, due to fixed prefix checks `APPABZ_` (both cases are supported now, with and without prefix)
- An old `dc-interface` from `bdp-core` has been used

I will test it now and put it on production, if ready...

**Comment by Piiit** [comment]
@rcavaliere @bertolla 
Tested on our with `PM10` and station codes `AB3` and `RE1` with measurement date `2019-02-19T10:00:00`, where both had been inserted correctly. All values with `-1` got skipped. 
I think that is correct. 

@rcavaliere If you agree, I put it on production now...

**Comment by Piiit** [comment]
@rcavaliere On production :-)

**Comment by rcavaliere** [comment]
@bertolla why do we have some stations set as active = FALSE even if we receive data? These stations are not available on the front-end side!!!

**Comment by bertolla** [comment]
This is due a misinterpretation of the field origin. If we change the origin string of the datacollector it should work fine. On the test-server there must be the same situation. Origin is not referred to the data itself but to the datacollector. Just think about synchronization works between stations, you can also check the code in class Station to get a better grasp of it.

**Comment by rcavaliere** [comment]
Sorry, isn't set automatically depending on the fact that the web-service provides info on these stations? And how can we fix this problem?

**Comment by bertolla** [comment]
Yeah, but different webservices, provide different set of stations. We compare between the set we have in the db and the set we get from a dc. These lines of code should be autoexplaining: https://github.com/idm-suedtirol/bdp-core/blob/ecff9289f23c7e5c626339100aeaaa09caf4f734/dal/src/main/java/it/bz/idm/bdp/dal/Station.java#L376

**Comment by rcavaliere** [comment]
OK, can you implement this?

**Comment by bertolla** [comment]
We just need to change origin filed from appabz to for example 'appabz-open'. I will do it now
