### ISSUE TITLE
As an air quality expert, I want to see the new meteo data stream from the Province of Trento integrated in the ODH infrastructure

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/bdp-commons#50]
- [x] adapt data-collectors CI pipeline 
- [x] create testing pipeline
- [x] deploy to testing server
- [x] EDP makes pull request, incl. documentation and test cases (week 5)
- [x] DC in testing environment (week 6)
- [ ] DC in production environment (week 7)

**Comment by bertolla** [comment]
@rcavaliere can be tested by checking data in our testdatabase. To me it seems ok.

**Comment by rcavaliere** [comment]
@bertolla there are a few things to be de discussed with EDP during the today's sprint meeting. Probably there is the need to make some slight modifications to the DC first.

**Comment by rcavaliere** [comment]
Updated plan:

- EDP makes pull request, incl. documentation and test cases (week 5)
- DC in testing environment (week 6)
- DC in production environment (week 7)
Complete planning available on https://docs.google.com/spreadsheets/d/1N5yXmKPDLeSUVivEmeLzpCAWB2p3YPMIAOIclLtjaOg/edit#gid=0

**Comment by Piiit** [comment]
@rcavaliere This means that we cannot not do anything until the end of this sprint, we just have to wait for EDP. Hence, I move this issue back to backlog for another sprint planning.

**Comment by Piiit** [comment]
@rcavaliere It is on our testing environment... please test. I will test it as well via SQL

**Comment by Piiit** [comment]
@rcavaliere  The test server has problems deploying new collectors... to many test applications I guess. I will let you know

**Comment by Piiit** [comment]
I can see some meteo measurements... It seems to work.

**Comment by rcavaliere** [comment]
Data completeness check completed, specifications fulfilled. We have in the table station also old stations which do not send data anymore, with attribute ACTIVE set as FALSE. Will these stations be visible on the API?

**Comment by bertolla** [comment]
no they won't as discussed previously
